tap "homebrew/bundle"
#tap "homebrew/cask"
#tap "homebrew/core"

brew "git"
brew "neofetch"
brew "neovim"
brew "tmux"
brew "zsh"
cask "1password"
cask "balenaetcher"
cask "brave-browser"
cask "discord"
cask "docker"
cask "figma"
cask "iterm2"
cask "notion"
cask "rider"
cask "slack"
cask "sourcetree"
cask "visual-studio-code"

